### ISSUE TITLE
Feature 'dom-overlay' is not supported for mode: immersive-vr

### ISSUE THREAD

**Issue by ivnnv** [immersive-web/dom-overlays#35]
Why overlays are not supported on `immersive-vr` sessions?

They are super useful in case you want to have something displayed all the time in the view no matter what is doing (HUD, Time or Weather information are good examples).

Most times it is an overkill or it is too difficult difficult to make this information displayed/merged at the gl the gl, this is specially an issue on Chrome Android because it completely launches the VR app instead staying at Chrome itself full-screened.

**Comment by AdaRoseCannon** [comment]
The standard does have suggestions for how browsers should implement it for immersive-vr sessions but no one has implemented that yet.

**Comment by klausw** [comment]
The specification of the feature should be compatible with `immersive-vr` sessions, it's a separate question if it's implemented in any particular user agent for that mode. At this time, there aren't any plans to implement a VR mode DOM overlay for Chrome on Android.

**Comment by ivnnv** [comment]
Thanks for the prompt response guys, In this meantime I got to have a quick read some of the related issues on this topic and the fact that capability is deferred, so looking forward for any major browser to make the first move because it is neither working on iOS Safari at least as it is intented to work on this proposed API.

But at least (surprisingly) iOS Safari allows to accomplish something similar as their "landscape full-screenish" implementation allows having html elements floating at the same time the main canvas is filling the screen when on a immersive-vr session.

**Comment by ivnnv** [comment]
Closing this and leaving the above for the record.
