### ISSUE TITLE
CSS Backdrop FIlter Behaviour

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/dom-overlays#36]
CSS has a cool property called [backdrop filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter).

It defines how content underneath a semi-transparent object gets filtered before displayed.

Do we have defined behaviour for how that should work with dom-overlays? 

It would be neat if it did work to have beautiful frosted glass HTML interfaces especially in head mounted use cases.

![image](https://user-images.githubusercontent.com/4225330/100238738-726ee680-2f28-11eb-8100-daf92f457b41.png)

**Comment by klausw** [comment]
Yes, there is specified behavior, see https://immersive-web.github.io/dom-overlays/#css-pseudo-class

> The overlay element is a [backdrop root](https://drafts.fxtf.org/filter-effects-2/#backdrop-root).
> 
> NOTE: Backdrop filter effects on the DOM overlay element or its descendants do not modify the AR camera image (if applicable) or the rendered content drawn to the immersive session’s XRWebGLLayer.

While it would indeed be cool if this could work, it would be a challenge to implement. The current smartphone AR implementation composes the camera data and GL drawn content separately from the DOM content, so the needed source pixel data for filtering isn't currently available in the DOM compositor. While this would potentially be fixable for smartphone AR, it's even more difficult for a see-through AR headset. That may not have a color camera image to use as input for compositing, and it would be tricky to do this correctly for each eye, especially if it's an additive-only display that can't darken the camera image.

**Comment by AdaRoseCannon** [comment]
Ah this makes sense, thanks for the fast reply :D
